AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template with two Lambda functions and one S3 bucket
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-sam-bucket
  GetOnlyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetOnlyFunction
      CodeUri: s3://my-sam-bucket/adc4e69008b764d662ace5c1a372039b
      Handler: app.lambda_handler
      Runtime: python3.10
      Policies:
      - S3ReadPolicy:
          BucketName: my-sam-bucket
    Metadata:
      SamResourceId: GetOnlyFunction
  GetPutFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetPutFunction
      CodeUri: s3://my-sam-bucket/0c6c0980fa59e07e64f3af93fcdf8d98
      Handler: app.lambda_handler
      Runtime: python3.10
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:GetObject
          - s3:PutObject
          Resource:
            Fn::Sub: arn:aws:s3:::my-sam-bucket/*
    Metadata:
      SamResourceId: GetPutFunction
